url: https://islp-bolivia.github.io/
baseurl: https://islp-bolivia.github.io/
# Site settings
title: Alfabetización Estadística Bolivia 
email: mailto:islp.bolivia@gmail.com
description: "Competencia Boliviana de Posters Estadísticos. Participa!!! Inscripciones abiertas hasta Octubre/2020"


# Team names, titles and social links
people:
#- name: Instituto Nacional de Estadística
# pic: ine
#  position: Estado Plurinacional de Bolivia
 # social:
  #  - title: twitter
#      url: https://twitter.com/ineoficialbo?lang=es
 #   - title: facebook
 #     url: https://www.facebook.com/ineboliviaoficial/
 #   - title: dribbble
  #    url: https://www.ine.gob.bo/
#- name: Carrera de Economía - La Paz 
#  pic: ucb
#  position: Universidad Católica Boliviana
#  social:
#    - title: dribbble
#      url: http://lpz.ucb.edu.bo/Forms/ProgramasAcademicos/Pregrado/ECO/ECO.aspx

- name: Fundación Aru
  pic: arulogo
  position: Instituto de Investigación
  social:
    - title: twitter
      url: https://twitter.com/arufoundation?lang=es
    - title: facebook
      url: https://www.facebook.com/FundacionARU
    - title: dribbble
      url: https://www.aru.org.bo/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/IslpBolivia
  - title: facebook
    url: https://www.facebook.com/islpBolivia/

# Postal address (add as many lines as necessary)
address:
  - line: La Paz - Bolivia

# Build settings
markdown: kramdown
permalink: pretty